version: '3.3'

services:
  encode1: &base
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: 'encode1.dev.kinsro.local'
    command: '/usr/sbin/sshd -D'
    ports:
      - '34220:22'
    stdin_open: true
    tty: true

  encode2:
    <<: *base
    hostname: 'encode2.dev.kinsro.local'
    ports:
      - '34221:22'

  media1:
    <<: *base
    hostname: 'media1.dev.kinsro.local'
    ports:
      - '34222:22'
