version: '3.3'

services:
  encode1: &base
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: 'encode1.dev.kinsro.local'
    command: 'tail -f /dev/null'

  encode2:
    <<: *base
    hostname: 'encode2.dev.kinsro.local'

  media:
    <<: *base
    hostname: 'media.dev.kinsro.local'
