- name: 'Install nfs-common'
  apt:
    name: nfs-common
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: 'mkdir video1'
  file:
    owner: pi
    group: pi
    recurse: yes
    path: /media/video1
    state: directory
  become: yes

- name: 'mount video1'
  mount:
    name: /media/video1
    src: '{{ storage_host }}:{{ item }}'
    fstype: nfs
    opts: 'rsize=8192,wsize=8192'
    state: mounted
  with_items: '{{ storages }}'
  become: yes
