#! /bin/sh

main() {
  local MEDIA="10.0.1.110"
  local ENCODE="10.0.1.100"

  deploy_encode "$MEDIA,$ENCODE"
  deploy_bin "$MEDIA,$ENCODE"
  deploy_front "$MEDIA"
}

deploy_bin() {
  local SERVERS=$1
  local IFS=$',' 

  for ITEM in $SERVERS 
  do
    local LOGIN="pi@$ITEM"
    ssh $LOGIN "mkdir -p ~/bin"
    ssh $LOGIN "mkdir -p ~/.config/kinsro"
    scp .env.production "$LOGIN:.config/kinsro/.env"
    scp build/kinsro_linux_arm32 "$LOGIN:bin/kinsro"
    ssh $LOGIN "chmod +x ~/bin/kinsro"
  done
}

deploy_encode() {
  local SERVERS=$1
  local IFS=$',' 

  for ITEM in $SERVERS 
  do
    local LOGIN="pi@$ITEM"
    ssh $LOGIN "mkdir -p ~/encode"
    scp assets/ts2mp4.sh "$LOGIN:encode/"
    scp assets/ts2mp4.ffpreset "$LOGIN:encode/"
    scp assets/recorded-command "$LOGIN:encode/"
    ssh $LOGIN "chmod +x ~/encode/recorded-command"
  done
}

deploy_front() {
  local SERVERS=$1
  local IFS=$',' 

  for ITEM in $SERVERS 
  do
    local LOGIN="pi@$ITEM"
    ssh $LOGIN "rm -rf /var/www/kinsro/*"
    scp build/front/* "$LOGIN:/var/www/kinsro"
    scp assets/index.html "$LOGIN:/var/www/kinsro"
  done
}

main