- name: 'Create nginx user'
  user:
    name: nginx
  become: yes

- name: 'Install nginx'
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: 'Start nginx'
  service:
    name: nginx
    enabled: yes
  become: yes

- name: 'Copy mime.types'
  copy:
    src: ./mime.types
    dest: /etc/nginx/mime.types
  become: yes

- name: 'Copy kinsro.conf'
  copy:
    src: ./kinsro.conf
    dest: /etc/nginx/sites-available/kinsro.conf
  become: yes

- name: 'Create symlink'
  file:
    src: /etc/nginx/sites-available/kinsro.conf
    dest: /etc/nginx/sites-enabled/kinsro.conf
    remote_src: yes
    state: link
  become: yes

- name: 'Create public dir'
  file:
    path: /var/www/kinsro
    state: directory
    mode: '0755'
    owner: pi
    group: pi
  become: yes

- name: 'Reload Nginx'
  service:
    name: nginx
    state: reloaded
  become: yes
