- name: 'mkdir encode'
  file:
    path: $HOME/encode
    state: directory
    mode: '0755'

- name: 'Copy recorded-command'
  copy:
    src: ./recorded-command
    dest: $HOME/encode/recorded-command
    mode: '0744'

- name: 'Copy bulk-encode command'
  copy:
    src: ./bulk-encode
    dest: $HOME/encode/bulk-encode
    mode: '0744'

- name: 'Copy encode command'
  copy:
    src: ./ts2mp4.sh
    dest: $HOME/encode/ts2mp4.sh

- name: 'Copy ffmpeg preset'
  copy:
    src: ./ts2mp4.ffpreset
    dest: $HOME/encode/ts2mp4.ffpreset
