#!/bin/sh

recorded(){
  local TS=$1
  local PROGRAM=$2

  local BASE=$(basename "$TS" .ts)
  local OUT_JSON="$BASE.json"
  local LOG="$BASE.log"
  local FINISH="$BASE.finish"
  local TMP_DIR=$(dirname "$TS")

  echo "$PROGRAM" > "$TMP_DIR/$OUT_JSON"
  echo "$PROGRAM" > "$TMP_DIR/$OUT_JSON"
  echo "home: $HOME" >> /tmp/encode_log
  echo "user: $USER" >> /tmp/encode_log

  DOTENV_PATH=/home/pi/.config/kinsro/.env /home/pi/bin/kinsro encode $TS > "$TMP_DIR/$LOG"
}

recorded $1 $2